using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CityWeather;
//
//    var cityForecast = CityForecast.FromJson(jsonString);

namespace CityWeather
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CityForecast
    {
        [JsonProperty("data")]
        public List<Datum> Data { get; set; }

        [JsonProperty("city_name")]
        public string CityName { get; set; }

        [JsonProperty("lon")]
        public string Lon { get; set; }

        [JsonProperty("timezone")]
        public string Timezone { get; set; }

        [JsonProperty("lat")]
        public string Lat { get; set; }

        [JsonProperty("country_code")]
        public string CountryCode { get; set; }

        [JsonProperty("state_code")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long StateCode { get; set; }
    }

    public partial class Datum
    {
        [JsonProperty("moonrise_ts")]
        public long MoonriseTs { get; set; }

        [JsonProperty("wind_cdir")]
        public string WindCdir { get; set; }

        [JsonProperty("rh")]
        public long Rh { get; set; }

        [JsonProperty("pres")]
        public double Pres { get; set; }

        [JsonProperty("high_temp")]
        public double HighTemp { get; set; }

        [JsonProperty("sunset_ts")]
        public long SunsetTs { get; set; }

        [JsonProperty("ozone")]
        public double Ozone { get; set; }

        [JsonProperty("moon_phase")]
        public double MoonPhase { get; set; }

        [JsonProperty("wind_gust_spd")]
        public double WindGustSpd { get; set; }

        [JsonProperty("snow_depth")]
        public long SnowDepth { get; set; }

        [JsonProperty("clouds")]
        public long Clouds { get; set; }

        [JsonProperty("ts")]
        public long Ts { get; set; }

        [JsonProperty("sunrise_ts")]
        public long SunriseTs { get; set; }

        [JsonProperty("app_min_temp")]
        public double AppMinTemp { get; set; }

        [JsonProperty("wind_spd")]
        public double WindSpd { get; set; }

        [JsonProperty("pop")]
        public long Pop { get; set; }

        [JsonProperty("wind_cdir_full")]
        public string WindCdirFull { get; set; }

        [JsonProperty("slp")]
        public double Slp { get; set; }

        [JsonProperty("valid_date")]
        public DateTimeOffset ValidDate { get; set; }

        [JsonProperty("app_max_temp")]
        public double AppMaxTemp { get; set; }

        [JsonProperty("vis")]
        public long Vis { get; set; }

        [JsonProperty("dewpt")]
        public double Dewpt { get; set; }

        [JsonProperty("snow")]
        public long Snow { get; set; }

        [JsonProperty("uv")]
        public double Uv { get; set; }

        [JsonProperty("weather")]
        public Weather Weather { get; set; }

        [JsonProperty("wind_dir")]
        public long WindDir { get; set; }

        [JsonProperty("max_dhi")]
        public object MaxDhi { get; set; }

        [JsonProperty("clouds_hi")]
        public long CloudsHi { get; set; }

        [JsonProperty("precip")]
        public double Precip { get; set; }

        [JsonProperty("low_temp")]
        public double LowTemp { get; set; }

        [JsonProperty("max_temp")]
        public double MaxTemp { get; set; }

        [JsonProperty("moonset_ts")]
        public long MoonsetTs { get; set; }

        [JsonProperty("datetime")]
        public DateTimeOffset Datetime { get; set; }

        [JsonProperty("temp")]
        public double Temp { get; set; }

        [JsonProperty("min_temp")]
        public double MinTemp { get; set; }

        [JsonProperty("clouds_mid")]
        public long CloudsMid { get; set; }

        [JsonProperty("clouds_low")]
        public long CloudsLow { get; set; }
    }

    public partial class Weather
    {
        [JsonProperty("icon")]
        public string Icon { get; set; }

        [JsonProperty("code")]
        public long Code { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class CityForecast
    {
        public static CityForecast FromJson(string json) => JsonConvert.DeserializeObject<CityForecast>(json, CityWeather.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this CityForecast self) => JsonConvert.SerializeObject(self, CityWeather.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
